### ISSUE TITLE
Unable to run - debian stable

### ISSUE THREAD

**Issue by mrinterestfull** [system76/beebee#10]
git clone https://github.com/system76/beebee.git

`mix deps.get`
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  mix.exs:11: BeeBee.Mixfile.project/0

Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  artificery 0.2.6
  cors_plug 1.1.2
  cowboy 1.0.4
  cowlib 1.0.2
  deep_merge 0.2.0
  distillery 2.0.12
  edeliver 1.6.0
  env_config_provider 0.1.0
  eredis 1.0.8
  exredis 0.2.4
  plug 1.1.4
  poison 2.1.0
  ranch 1.2.1
  toml 0.5.2
* Getting cors_plug (Hex package)
* Getting cowboy (Hex package)
* Getting plug (Hex package)
* Getting exredis (Hex package)
* Getting poison (Hex package)
* Getting distillery (Hex package)
* Getting edeliver (Hex package)
* Getting env_config_provider (Hex package)
* Getting toml (Hex package)
* Getting deep_merge (Hex package)
* Getting artificery (Hex package)
* Getting eredis (Hex package)
* Getting cowlib (Hex package)
* Getting ranch (Hex package)

`mix conform.configure`
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  mix.exs:11: BeeBee.Mixfile.project/0

==> eredis (compile)
src/eredis_parser.erl:none: undefined parse transform 'eunit_autoexport'
Compiling src/eredis_parser.erl failed:
ERROR: compile failed while processing /home/lucas/Downloads/tmp/elxir/beebee/deps/eredis: rebar_abort
** (Mix) Could not compile dependency :eredis, "/home/lucas/.mix/rebar compile skip_deps=true deps_dir="/home/lucas/Downloads/tmp/elxir/beebee/_build/dev/lib"" command failed. You can recompile this dependency with "mix deps.compile eredis", update it with "mix deps.update eredis" or clean it with "mix deps.clean eredis"

` elixir -v`
Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

Elixir 1.10.3 (compiled with Erlang/OTP 22)

**Comment by codeadict** [comment]
You were using an Erlang OTP version that was not supported, new commit just merged should fix that :)
